spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=wb_schema
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher